### ISSUE TITLE
Remove default-constructibility requirement in ChainRange

### ISSUE THREAD

**Issue by Hazurl** [simonask/rx-ranges#40]
https://github.com/simonask/rx-ranges/blob/develop/include/rx/ranges.hpp#L2053
`_get` should not call itself if `sizeof...(rest) == 0`.

**Comment by simonask** [comment]
That line exists solely to silence "no return statement in non-void function" warnings. I wonder if calling `std::abort()` and adding `[[noreturn]]` would be more elegant.

**Comment by Hazurl** [comment]
~~No. You just need to not create the `_get` method with an empty index_sequence, and never call it.~~
Nevermind you always get a branch with no return statement with my solution.

**Comment by Hazurl** [comment]
I end up using your solution as this snippet is ugly (returning the last element if not  in range):
```cpp
    template <size_t i, size_t... rest>
    constexpr output_type _get(std::index_sequence<i, rest...>) const {
        RX_ASSERT(current_input < sizeof...(Rs)); // chain was at end!
        if constexpr (sizeof...(rest) <= 0) {
            return std::get<i>(inputs).get();
        } else {
            if (i == current_input) {
                return std::get<i>(inputs).get();
            } else {
                return _get(std::index_sequence<rest...>{});
            }
        }
    }
```

**Comment by simonask** [comment]
And now I realize that the drawback of using `std::abort()` here is that `ChainRange` can no longer be used at all in a `constexpr` context. I wonder if `throw` can be used instead, but I'm not sure because I think the recursion base case will be compiled for any instantiation of `get<size_t...>`. This might have already been true with the assertion.

Alexandrescu has a solution here, but nobody seems to know why it works: https://akrzemi1.wordpress.com/2017/05/18/asserts-in-constexpr-functions/

Hmm. I think it's more important to lift the default-constructibility requirement than to remain `constexpr`. I'll have a look at ensuring `constexpr`-ness later.
